export const RegistrationRequest = [
    {
        id: 1,
        nombre_contacto: "CHRISTOPHE ALEXIS LE MAILLOT",
        email: "angelica@zerogravity.com.mx",
        telefono: "09841430764",
        codigo: "107258",
        nombre_establecimiento: "zero Gravity",
        archivo_pdf: "1714665014.pdf",
        mensaje: "-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 10:50:14",
        fecha_actualizacion: "2024-05-02 16:50:08"
    },
    {
        id: 2,
        nombre_contacto: "MARTIN HERNANDEZ LOPEZ",
        email: "cdelmar2008@gmail.com",
        telefono: "9848034334",
        codigo: "2161",
        nombre_establecimiento: "HOTEL CASTILLO DEL MAR",
        archivo_pdf: "1714665936.pdf",
        mensaje: "-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 11:05:36",
        fecha_actualizacion: "2024-05-02 16:50:00"
    },
    {
        id: 3,
        nombre_contacto: "MARTIN HERNANDEZ LOPEZ",
        email: "ceciliaherflo@gmail.com",
        telefono: "9848034334",
        codigo: "7016",
        nombre_establecimiento: "HOTEL ATLANTIDA",
        archivo_pdf: "1714666046.pdf",
        mensaje: "-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 11:07:26",
        fecha_actualizacion: "2024-05-02 16:49:52"
    },
    {
        id: 4,
        nombre_contacto: "MATTEO PREVEDEL",
        email: "playapiave2015@gmail.com",
        telefono: "9841328449",
        codigo: "112074",
        nombre_establecimiento: "PLAYA PIAVE",
        archivo_pdf: "1714674593.pdf",
        mensaje: "-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 13:29:53",
        fecha_actualizacion: "2024-05-02 16:49:44"
    },
    {
        id: 5,
        nombre_contacto: "Federico Andres Sancho Mesny",
        email: "contador.h52@dchotels.mx",
        telefono: "9983301835",
        codigo: "111360",
        nombre_establecimiento: "Hotel 52",
        archivo_pdf: "1714674761.pdf",
        mensaje: "-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 13:32:41",
        fecha_actualizacion: "2024-05-02 16:49:36"
    },
    /*{
        id: 6,
        nombre_contacto: "ANTONIO JOSE RODRIGUEZ RODRIGUEZ",
        email: "fiscalista.mx@sandos.com",
        telefono: "9841659217",
        codigo: "2185",
        nombre_establecimiento: "HOTEL SANDOS CARACOL",
        archivo_pdf: "1714678133.pdf",
        mensaje: "-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 14:28:53",
        fecha_actualizacion: "2024-05-02 16:49:17"
    },
    {
        id: 7,
        nombre_contacto: "LIDIA GARCIA ALONSO",
        email: "lidia.garcia@viceroyhotelsandresorts.com",
        telefono: "9848773000",
        codigo: "8737",
        nombre_establecimiento: "Hotel Viceroy Riviera Maya",
        archivo_pdf: "1714678647.pdf",
        mensaje: "-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 14:37:27",
        fecha_actualizacion: "2024-05-02 16:49:07"
    },
    {
        id: 8,
        nombre_contacto: "LIDIA GARCIA ALONSO",
        email: "lidia.garcia@viceroyhotelsandresorts.com",
        telefono: "9848773000",
        codigo: "8737",
        nombre_establecimiento: "HOTEL VICEROY RIVIERA MAYA",
        archivo_pdf: "1714687524.pdf",
        mensaje: "Buenas tardes, el acta constitutiva esta correcto, pero haría falta que en el mismo archivo pdf se anexen los otros documentos solicitados.\n\n-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.\n\nExcelente tarde, saludos.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-02 17:05:24",
        fecha_actualizacion: "2024-05-02 17:45:15"
    },
    {
        id: 11,
        nombre_contacto: "Erasmo Ivan Lozano Martinez",
        email: "hsa990820@gmail.com",
        telefono: "9848730884",
        codigo: "2073",
        nombre_establecimiento: "Hotel Lunata",
        archivo_pdf: "1714749799.PDF",
        mensaje: "Estimado contribuyente favor de anexar los siguientes documentos  dependiendo si es persona fisca o moral. \n\n-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-03 10:23:19",
        fecha_actualizacion: "2024-05-03 11:16:53"
    },
    {
        id: 12,
        nombre_contacto: "CHAI ABRAHAM GORMEZ",
        email: "gte.contable2@cetinajimenez.com",
        telefono: "9841477556",
        codigo: "105840",
        nombre_establecimiento: "THE GREEN VILLAGE HOTEL BOUTIQUE",
        archivo_pdf: "1714751528.pdf",
        mensaje: "Estimado contribuyente favor de anexar la documnetación correspondiente segun su regimen en este caso ya sea persona fisica o moral. Saludos.\n\n-PERSONA MORAL: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Acta Constitutiva.\n2: Poder Notarial (en caso de tenerlo).\n3: Identificaciones Oficiales correspondientes.\n4: Constancia de Situación Fiscal Actualizada.\n5: Licencia de Funcionamiento vigente.\n\n\n-PERSONA FÍSICA: Anexar en un solo documento pdf, en el orden como se presenta, los siguientes archivos:\n1: Constancia de Situación Fiscal Actualizada.\n2: Identificación Oficial Vigente.\n3: Licencia de Funcionamiento Vigente.\n4: Carta Poder Notariada con las identificaciones correspondientes.",
        estado: 0,
        flag: -1,
        fecha_creacion: "2024-05-03 10:52:08",
        fecha_actualizacion: "2024-05-03 11:18:45"
    }*/
]
